updated pnx and build script.

diff --git a/appdir/pnx b/appdir/pnx
--- a/appdir/pnx
+++ b/appdir/pnx
@@ -1,6 +1,4 @@
-#!/bin/sh
-
-set -x
+#! /bin/sh
 
 #############################################################################################################################################################################
 #   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
@@ -26,158 +24,131 @@ set -x
 #############################################################################################################################################################################
 
 
-# ##########################
-# ####    PNX v1.0.3    ####
-# ##########################
+# #########################
+# ####   pnx v1.0.0.    ###
+# #########################
+
+err () { printf "${0##*/}: \e[31merror:\e[0m: %b\n" "$@" >&2; exit $?; }
+put () { printf "%b\n" "$@" >&2; }
 
 
-if [ "$EUID" -ne 0 ]
-  then _e "Please run PNX as root.\nTry with: sudo ${0##*/}\n Exiting..."
-  exit
-fi
+#	set pnx directories.
 
-_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }
+pnx_root=~/.pnx
+pnx_cache="$pnx_root/var/lib/pacman"
 
 
-# -- Set PNX directories.
+#	version and commit that generated this build.
 
-PNX_ROOT="/home/.pnx"
-PNX_CACHE="/home/.pnx/var/lib/pacman"
-PNX_KEYRINGS="/usr/share/pacman/keyrings"
+_pnx_version=1.0.0
+pnx_commit_hash=@_COMMIT@
 
 
-# -- Flags for the command.
+#	flag parsing.
 
 case "$1" in
-
 	-h|--help)
-
-		echo "${0##*/}: Welcome to PNX!. \n"
-		echo "Description: \n"
-		echo "    PNX is a wrapper for Pacman. Pacman is a package management utility that tracks installed packages on a Linux system."
-		echo "    This wrapper allows the user to use Pacman on a Linux distribution that is not a derivative of Arch Linux without conflicts with"
-		echo "    the distribution existing package manager.  \n"
-		echo "    Report bugs at: https://github.com/Nitrux/pnx. \n"
-		echo "Flags: \n"
-		echo "    --initialize, Create PNX root directory."
-		echo "    --key, Use pacman-key: pacman-key - manage pacman's list of trusted keys."
-		echo "    --repo, Use repo-add: repo-add - package database maintenance utility."
-		echo "    --launch, Launch a program installed using PNX."
-		echo "    --makepkg, Create a package from a PKGBUILD (Experimental)."
-		echo "    --aur, Download and install apackage from the AUR using Yay (Experimental)."
-		echo "    --remove-dirs, Remove PNX directories."
-		echo "    --debug, Run PNX with debug on."
-		echo "    --release, Show the version. \n"
-		echo "Usage: \n"
-		echo "    When no flag is specified, PNX will default to package management."
-		echo "        pnx <operation> [options] [targets]"
-		echo "        pnx <flag> <operation> [options] [targets] \n"
-		echo "Examples: \n"
-		echo "sudo pnx -S inkscape"
-		echo "    To install a package using PNX use the same syntax as Pacman."
-		echo "    For example, pnx -S inkscape will download and install inkscape and all the packages it depends on."
-		echo "sudo pnx -Syu"
-		echo "    Update package list and upgrade all packages afterwards."
-		echo "sudo pnx --key --init"
-		echo "    Ensure the keyring is properly initialized and has the required access permissions."
-		echo "sudo pnx --repo --verify"
-		echo "    Verify the PGP signature of the database before updating the database."
-		echo "pnx --launch inkscape"
-		echo "    This will execute a program installed using PNX."
-		echo "\n"
-		exit
-
-	;;
-
-	--initialize)
-
-		[ -d $PNX_ROOT ] && _e "${0##*/} directory already exist!.\nExiting...\n " || echo "${0##*/} directories do not exist, creating...\n\n Please run these commands to start using PNX:\n sudo ${0##*/} --key --init\n sudo ${0##*/} --key --populate\n " && mkdir -p $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS && cp -a $APPDIR/usr/share/pacman/keyrings/* $PNX_KEYRINGS
-		exit
-
-	;;
-
-	--key)
-
-		export \
-			LIBRARY=$APPDIR/usr/share/makepkg &&
-		pacman-key "$2"
-		exit
-
-	;;
-
-	--repo)
-
-		repo-add "$2"
-		exit
-
+		put \
+			 "Welcome to pnx!" \
+			 "Description:" \
+			 "    pnx is a wrapper for Pacman. Pacman is a package management utility that tracks installed packages on a Linux system." \
+			 "    This wrapper allows the user to use Pacman on a Linux distribution that is not a derivative of Arch Linux without" \
+			 "    conflicts with the distribution existing package manager." \
+			 "    Report bugs at: https://github.com/Nitrux/pnx." \
+			 "Flags:" \
+			 "    --initialize, Create pnx root directory." \
+			 "    --key, Use pacman-key: pacman-key - manage pacman's list of trusted keys." \
+			 "    --repo, Use repo-add: repo-add - package database maintenance utility." \
+			 "    --launch, Launch a program installed using pnx." \
+			 "    --remove-dirs, Remove pnx directories." \
+			 "    --debug, Run pnx with debug on." \
+			 "    --release, Show the version." \
+			 "Usage:" \
+			 "    When no flag is specified, pnx will default to package management." \
+			 "        pnx <operation> [options] [targets]" \
+			 "        pnx <flag> <operation> [options] [targets]" \
+			 "Examples:" \
+			 "pnx -S inkscape" \
+			 "    To install a package using pnx use the same syntax as Pacman." \
+			 "    For example, pnx -S inkscape will download and install inkscape and all the packages it depends on." \
+			 "pnx -Syu" \
+			 "    Update package list and upgrade all packages afterwards." \
+			 "pnx --key --init" \
+			 "    Ensure the keyring is properly initialized and has the required access permissions." \
+			 "pnx --repo --verify" \
+			 "    Verify the PGP signature of the database before updating the database." \
+			 "pnx --launch inkscape" \
+			 "    This will execute a program installed using pnx."
 	;;
 
 	--launch)
-
-		pnx-launch "$@"
-		exit
-	;;
-
-	--makepkg)
-
 		export \
-			LIBRARY=$APPDIR/usr/share/makepkg &&
-		makepkg "$2"
-		exit
+			PATH=$pnx_root/usr/bin/:$pnx_root/usr/sbin/:$pnx_root/usr/games/:$pnx_root/bin/:$pnx_root/sbin/ \
+			LD_LIBRARY_PATH=$pnx_root/usr/lib/:$pnx_root/usr/lib/i386-linux-gnu/:$pnx_root/usr/lib/x86_64-linux-gnu/:$pnx_root/usr/lib32/:$pnx_root/usr/lib64/:$pnx_root/lib/:$pnx_root/lib/i386-linux-gnu/:$pnx_root/lib/x86_64-linux-gnu/:$pnx_root/lib32/:$pnx_root/lib64/:$pnx_root/usr/lib/dri/:$pnx_root/usr/lib/pulseaudio/:$pnx_root/usr/lib/gdk-pixbuf-2.0/:$pnx_root/gs-plugins-13/:$pnx_root/usr/lib/systemd/:$pnx_root/usr/lib/samba/:$pnx_root/usr/lib/girepository-1.0/:$pnx_root/usr/lib/WebKitNetworkProcess/:$pnx_root/usr/lib/epiphany/:$pnx_root/usr/lib/opera/:$pnx_root/usr/lib/firefox/ \
+			XDG_DATA_DIRS=$pnx_root/usr/share/ \
+			GSETTINGS_SCHEMA_DIR=$pnx_root/usr/share/glib-2.0/schemas/ \
+			QT_PLUGIN_PATH=$pnx_root/usr/lib/qt4/plugins/:$pnx_root/usr/lib/i386-linux-gnu/qt4/plugins/:$pnx_root/usr/lib/x86_64-linux-gnu/qt4/plugins/:$pnx_root/usr/lib32/qt4/plugins/:$pnx_root/usr/lib64/qt4/plugins/:$pnx_root/usr/lib/qt5/plugins/:$pnx_root/usr/lib/i386-linux-gnu/qt5/plugins/:$pnx_root/usr/lib/x86_64-linux-gnu/qt5/plugins/:$pnx_root/usr/lib32/qt5/plugins/:$pnx_root/usr/lib64/qt5/plugins/ \
+			TERM=xterm-256color \
+			GTK_PATH=$pnx_root/usr/lib/:$pnx_root/lib:$pnx_root/lib64
 
-	;;
-
-	--aur)
-
-		yay "$2"
-		exit
-
-	;;
-
-	--remove-dirs)
-
-		rm -R $PNX_ROOT
-		exit
-
-	;;
-
-	--debug)
-
-		set -x
-		shift
-
+		shift; exec "$@"
 	;;
 
 	--release)
-
-		echo "${0##*/}: version 1.0.3, 25th June 2020.\n "
-		echo "The license used for this file and its contents is: BSD-3-Clause. \n "
-		echo "Authors: \n"
-		echo "    Copyright <2020> <Uri Herrera <uri_herrera@nxos.org>>"
-		echo "    Copyright <2020> <Luis Lavaire <luis_lavaire@nxos.org>>\n "
-		echo "Made with ♥ by Nitrux Latinoamericana S.C.\n "
-		exit
-
+		put \
+			 "pnx: version $_pnx_version, 14th January 2020." \
+			 "The license used for this file and its contents is: BSD-3-Clause." \
+			 "Authors:" \
+			 "    Copyright <2020> <Uri Herrera <uri_herrera@nxos.org>>" \
+			 "    Copyright <2020> <Luis Lavaire <llavaire01@gmail.org>>" \
+			 "Made with ♥ by Nitrux Latinoamericana S.C."
 	;;
 
+	--initialize)
+		test \
+			-d $pnx_root \
+			-a -d $pnx_cache \
+			-a -d $PNX_KEYRINGS &&
+		err "Already initialized."
+
+		mkdir -p \
+			"$pnx_root" \
+			"$pnx_root/var/lib/pacman" \
+			"$pnx_cache" \
+			"$PNX_KEYRINGS"
+
+		pacman --noconfirm -r $pnx_root -Syu \
+			base bash readline ncurses util-linux coreutils libcap iputils which grep sudo \
+			acl archlinux-keyring attr bzip2 curl expat glibc gpgme libarchive openssl nss nspr \
+			libassuan libgpg-error libnghttp2 libssh2 lzo openssl pacman pacman-mirrorlist xz zlib \
+			krb5 e2fsprogs keyutils libidn2 libunistring gcc-libs lz4 libpsl icu libunistring zstd
+
+		 "$0" --key --init
+		 "$0" --key --populate
+	;;
+
+	--key)
+		export LIBRARY=$APPDIR/usr/share/makepkg
+		exec chroot "$pnx_root" pacman-key "$@"
+	;;
+
+	--repo)
+		exec runch "$pnx_root" repo-add "$@"
+	;;
+
+	--remove-dirs)
+		rm -rf "$pnx_root"
+		exit
+	;;
 esac
 
 
-# -- Probe for PNX root existence.
+#	probe for pnx root existence.
 
-test -d $PNX_ROOT ||
-	_e "${0##*/} has not been initialized. Please run: sudo ${0##*/} --initialize\nExiting...\n "
-
-
-# -- By default use Pacman if no flag is specified.
-
-	pacman "$@"
+test -d $pnx_root ||
+	err "pnx has not been initialized. Please run: ${0##*/} --initialize."
 
 
-# -- Integrate .desktop files from pnx directory into the user's directory after installing a program with Pacman.
+#	by default use pacman if no flag is specified.
 
-# for dot_d in $(pacman -r $PNX_ROOT -Qql | grep '\.desktop'); do
-# 	ln -sf $PNX_ROOT/$dot_d $HOME/.local/share/applications
-# done
-
-exit 0
+pacman -r "$pnx_root" "$@"
