update code

diff --git a/appdir/pnx b/appdir/pnx
--- a/appdir/pnx
+++ b/appdir/pnx
@@ -4,7 +4,7 @@
 #   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
 #                                                                                                                                                                           #
 #   Copyright <2020> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
-#   Copyright <2020> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                                 #
+#   Copyright <2020> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                               #
 #                                                                                                                                                                           #
 #   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
 #                                                                                                                                                                           #
@@ -28,20 +28,23 @@
 # ####    PNX v1.0.     ###
 # #########################
 
-_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }
 
-test $(id -u) -eq 0 ||
-	_e "Please run ${0##*/} as root: sudo ${0##*/}\n Exiting..."
+if [ "$EUID" -ne 0 ]
+  then _e "Please run PNX as root.\nTry with: sudo ${0##*/}\n Exiting..."
+  exit
+fi
+
+_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }
 
 
 # -- Set PNX directories.
 
-PNX_ROOT=/home/.pnx
-PNX_CACHE=/var/lib/pacman
-PNX_KEYRINGS=/usr/share/pacman/keyrings
+PNX_ROOT="/home/.pnx"
+PNX_CACHE="/var/lib/pacman"
+PNX_KEYRINGS="/usr/share/pacman/keyrings"
 
 
-#	Flags for the command.
+# -- Flags for the command.
 
 case "$1" in
 
@@ -59,7 +62,7 @@ case "$1" in
 		echo "    --repo, Use repo-add: repo-add - package database maintenance utility."
 		echo "    --launch, Launch a program installed using PNX."
 		echo "    --remove-dirs, Remove PNX directories."
-		echo "    --debug, Remove PNX root folder."
+		echo "    --debug, Run PNX with debug on."
 		echo "    --release, Show the version. \n"
 		echo "Usage: \n"
 		echo "    When no flag is specified, PNX will default to package management."
@@ -84,38 +87,30 @@ case "$1" in
 
 	--initialize)
 
-		[ -d $PNX_ROOT -a -d $PNX_CACHE -a -d $PNX_KEYRINGS ] &&
-			_e "Environment already initialized.\nExiting...\n"
-
-		echo "Initializing...\n\n Please run these commands to start using PNX:\n sudo ${0##*/} --key --init\n sudo ${0##*/} --key --populate\n "
-		mkdir -p $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS
-		cp -av $APPDIR/usr/share/pacman/keyrings/* $PNX_KEYRINGS
-
+		[ -d $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS ] && _e "${0##*/} directories already exist!.\nExiting...\n " || echo "${0##*/} directories do not exist, creating...\n\n Please run these commands to start using PNX:\n sudo ${0##*/} --key --init\n sudo ${0##*/} --key --populate\n " && mkdir -p $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS && cp -a $APPDIR/usr/share/pacman/keyrings/* $PNX_KEYRINGS
 		exit
 
 	;;
 
 	--key)
 
-		shift
-		export LIBRARY=$APPDIR/usr/share/makepkg
-		pacman-key "$@"
+		export \
+			LIBRARY=$APPDIR/usr/share/makepkg &&
+		pacman-key "$2"
 		exit
 
 	;;
 
 	--repo)
 
-		shift
-		repo-add "$@"
+		repo-add "$2"
 		exit
 
 	;;
 
 	--launch)
 
-		shift
-		pnx-launch "$@"
+		pnx-launch "$2"
 		exit
 
 	;;
@@ -149,12 +144,21 @@ case "$1" in
 esac
 
 
-#	Probe for PNX root existence.
+# -- Probe for PNX root existence.
 
 test -d $PNX_ROOT ||
 	_e "${0##*/} has not been initialized. Please run: sudo ${0##*/} --initialize\nExiting...\n "
 
 
-#	By default use Pacman if no flag is specified.
+# -- By default use Pacman if no flag is specified.
 
-pacman "$@"
+	pacman "$@"
+
+
+# -- Integrate .desktop files from PNX directory into the user's directory after installing a program with Pacman.
+
+# for dot_d in $(pacman -r $PNX_ROOT -Qql | grep '\.desktop'); do
+# 	ln -sf $PNX_ROOT/$dot_d $HOME/.local/share/applications
+# done
+
+exit 0
